[package]
name = "schafkopfliste"
version = "0.1.0"
authors = ["Björn Eyselein <bjoern.eyselein@uni-wuerzburg.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.10", features = ["serde"] }

rocket = "0.4.2"
rocket_contrib = { version = "0.4.2", default-features = false, features = ["json", "diesel_sqlite_pool", "uuid"] }
rocket_cors = "0.5.1"

uuid = { version = "0.8.1", features = ["v4", "serde"] }

diesel = { version = "1.4.3", features = ["chrono", "sqlite", "uuid"] }

serde = "1.0.104"
serde_derive= "1.0.104"
serde_json = "1.0.46"
