[debug]
address = "0.0.0.0"

[default]
port = 8008

[debug.databases]
schafkopfliste = { url = "postgres://skl:1234@localhost:5465/skl" }

[release.databases]
schafkopfliste = { url = "postgres://skl:1234@localhost/skl" }
