[development]
address = "0.0.0.0"

[global]
port = 8008

[development.databases]
schafkopfliste = { url = "postgres://skl:1234@localhost:5465/skl" }

[production.databases]
schafkopfliste = { url = "postgres://skl:1234@localhost/skl" }
